import os

APP_NAME = "MAIN-BASE-FOUNDATION"

PERSON_ID = "PRS-7K4M-2Q8N-6T1X"
INTERNAL_USER_ID = "0194F8A27C317B4E9D218A6F3C5B1E90"
USERNAME = "RAJESHKHANDELWALOFFICIAL"
DISPLAY_NAME = "👑 DR RAJESH KHANDELWAL IBC OFFICIAL 👑"

BUSINESS_ID = "BUS-2M7R-9Q4A-6T8C"
COMPANY_ID = "CMP-8D3F-6N1Q-4X9K"
SUPREME_ID = "SUP-9C4M-7X2K-6P8R"

EMAILS = [
    "DRRAJESHKHANDELWALIBCOFFICIAL@GMAIL.COM",
    "RAJESHKHANDELWAL@GMAIL.COM",
    "RAJESHKHANDELWAL468@GMAIL.COM",
    "RAJESHKHANDELWALOFFICIAL@GMAIL.COM",
    "RAJESHKHANDELWALOFFICIALS@GMAIL.COM",
    "DRRAJESHKHANDELWALIBC@GMAIL.COM",
    "INFO@RAJESHKHANDELWALOFFICIAL.COM"
]

ALIAS_NAMES = [
    "RAJESHKHANDELWAL",
    "RAJESHKHANDELWAL OFFICIAL",
    "SUPREME RAJESH KHANDELWAL",
    "SUPREME RAJESH KHANDELWAL OFFICIAL",
    "SUPREME DR RAJESH KHANDELWAL IBC",
    "SUPREME DR RAJESH KHANDELWAL IBC OFFICIAL",
    "DR RAJESH KHANDELWAL IBC",
    "DR RAJESH KHANDELWAL IBC OFFICIAL"
]

PORT = int(os.getenv("PORT", "10000"))
